branch-defaults:
  main:
    environment: Hellotrianglz-env
environment-defaults:
  Hellotrianglz-env:
    branch: null
    repository: null
global:
  application_name: hello_trianglz
  default_ec2_keyname: ecom
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: trianglz
  sc: git
  workspace_type: Application
